---
- name: Install Prometheus
  hosts: All
  become: yes
  tasks:
    - name: Add Prometheus APT key
      apt_key:
        url: https://packages.grafana.com/gpg.key
        state: present

    - name: Add Prometheus APT repository
      apt_repository:
        repo: deb https://packages.grafana.com/oss/deb stable main
        state: present

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Prometheus
      apt:
        name: prometheus
        state: present
